description: |
    Tag commits based on PR message
jobs:
    version-from-commit-subject:
        description: |
            Promote a commit a semantic version release. It assumes the context of a GitHub pull request, and promotion of the code to a new major/minor/patch version is based on information that must be contained in the subject of the commit that merges the pull request. Namely, the commit subject must include both a ticket reference, and the `[semver:FOO]` pattern, where FOO is major, minor, patch, or skip (to skip promotion). e.g. 'Merge pull request #XX from some-branch JIRA-123 [semver:minor]'
        executor: cli/default
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - 6b:ed:c8:48:7c:76:67:f3:88:82:f6:f8:a3:50:b8:85
            - run:
                command: <<include(scripts/configure-git.sh)>>
                name: Configure Git
            - run:
                command: <<include(scripts/01-get-tag-from-commit-subject.sh)>>
                name: Parse commit message and repo tags
            - run:
                command: <<include(scripts/02-decide-new-tag.sh)>>
                name: Create New Tag
version: 2.1
workflows:
    primary:
        jobs:
            - version-from-commit-subject:
                filters:
                    branches:
                        only:
                            - master

